import type { Lesson } from '../payload-types'
import { exampleCourseSlug } from '../lib/course-catalog'

// Authoring source for the first course import. Runtime pages read published CMS
// content, so subsequent edits in Payload remain authoritative.
type Block = { kind: 'p' | 'h3' | 'formula'; text: string } | { kind: 'list'; items: string[] } | { kind: 'link'; text: string; url: string }
const p = (text: string): Block => ({ kind: 'p', text })
const h = (text: string): Block => ({ kind: 'h3', text })
const f = (text: string): Block => ({ kind: 'formula', text })
const list = (...items: string[]): Block => ({ kind: 'list', items })
const link = (text: string, url: string): Block => ({ kind: 'link', text, url })
const textNode = (text: string) => ({ type: 'text', version: 1, text, detail: 0, format: 0, mode: 'normal', style: '' })
const element = { version: 1, direction: null, format: '' as const, indent: 0 }

export function richText(blocks: Block[]): Lesson['content'] {
  return { root: { ...element, type: 'root', children: blocks.map((block) => {
    if (block.kind === 'list') return { ...element, type: 'list', listType: 'bullet', tag: 'ul', start: 1,
      children: block.items.map((item, i) => ({ ...element, type: 'listitem', value: i + 1, children: [textNode(item)] })) }
    if (block.kind === 'link') return { ...element, type: 'paragraph', children: [{ ...element, type: 'link', fields: { linkType: 'custom', url: block.url, newTab: true }, children: [textNode(block.text)] }] }
    return { ...element, type: block.kind === 'h3' ? 'heading' : block.kind === 'formula' ? 'quote' : 'paragraph',
      ...(block.kind === 'h3' ? { tag: 'h3' } : {}), children: [textNode(block.text)] }
  }) } }
}

export const astrodynamicsCourse = {
  title: 'Foundations of Astrodynamics', slug: exampleCourseSlug, order: 20,
  objectives: [
    'Explain how Kepler’s observations and Newton’s mechanics describe the same orbital motion.',
    'Calculate orbital size, period, speed, specific energy and specific angular momentum with consistent units.',
    'Derive the two-body equation of relative motion and identify the assumptions behind it.',
    'Distinguish the different orbital periods and recognize when perturbations matter.',
  ].map((objective) => ({ objective })),
  description: richText([
    h('Section 1 · Astrodynamics Laws'),
    p('Why does a satellite keep falling without reaching the ground? This module connects Kepler’s description of orbits to Newton’s explanation of the forces behind them. Work through the laws, follow the derivations, then apply them to real orbital scales.'),
    p('This is the first complete module of Course II. Later sections on orbital geometry, reference frames, propagation and maneuvers are outside this module.'),
    p('Prerequisites: algebra, basic differentiation, vectors and the cross product. Estimated study time: about two hours, including the worked examples and practice. The course material is in English.'),
    p('Adapted from Richard L. Lachance, Ph.D., SꙨL Part II – Section 1 – Astrodynamics Laws, 85 slides. The web edition reorganizes repeated slides, develops the calculations and clarifies units and modeling assumptions. Slide references appear in each lesson.'),
  ]),
}

export const astrodynamicsOverview = richText([
  p('Course II develops the physical foundations needed to predict satellite motion. Its first available module, Astrodynamics Laws, connects observations of planetary motion to the equations used in spacecraft engineering.'),
  h('Section 1 · Astrodynamics Laws'),
  p('Kepler describes the orbit: an ellipse with the attracting body at one focus, equal areas swept in equal times, and a period that grows with the size of the orbit. A satellite therefore travels faster near periapsis and slower near apoapsis.'),
  f('T² = 4π²a³ / μ'),
  p('Here T is the orbital period, a is the semi-major axis and μ = G(M + m) is the gravitational parameter of the two-body system. For an artificial Earth satellite, μ ≈ GM⊕. Orbits with the same a around the same primary have the same Keplerian period.'),
  p('Newton explains the motion: inertia keeps the spacecraft moving, while gravity continuously bends its trajectory. Combining F = ma with universal gravitation gives an acceleration directed toward the primary, with magnitude μ/r².'),
  f('r̈ = −μr / |r|³'),
  p('Two conserved quantities make the motion easier to understand. Specific mechanical energy ε = v²/2 − μ/r determines the orbital size and whether the trajectory is bound. Specific angular momentum h = r × v fixes the orbital plane and explains Kepler’s law of areas. These quantities remain constant in the ideal, unperturbed two-body model.'),
  h('A first application'),
  p('Mars takes about 1.88 Earth years to orbit the Sun. Comparing its orbit with Earth’s gives a ≈ 1.88^(2/3) = 1.52 AU. The same period law helps engineers choose satellite orbits.'),
  h('Continue with the complete module'),
  p('The complete module includes nine lessons, step-by-step derivations, a circular-orbit calculator, worked examples and a self-check with explained answers. It also distinguishes orbital periods, explains free fall and develops the equation of relative motion.'),
  p('Source: Richard L. Lachance, Ph.D., SꙨL Part II – Section 1 – Astrodynamics Laws. Basic algebra and vectors are recommended.'),
])

const lessons: { slug: string; title: string; durationMinutes: number; slides: string; blocks: Block[] }[] = [
  { slug: 'astrodynamics-mission-and-notation', title: 'Astrodynamics, missions and notation', durationMinutes: 10, slides: '6–17', blocks: [
    h('What you will learn'),
    p('Locate astrodynamics within a space mission and read the symbols used throughout this module.'),
    h('An orbit serves a mission'),
    p('Astrodynamics applies mechanics to the motion of spacecraft under natural and artificial forces. It predicts trajectories, determines orbits from observations and supports decisions about launch, station keeping and maneuvers. Celestial mechanics provides the broader framework for natural bodies as well.'),
    p('The payload performs the mission: it may observe Earth, relay communications or conduct an experiment. The spacecraft bus supplies power, thermal control, structure, attitude control and data handling. Together they form the spacecraft.'),
    p('The launch system delivers the spacecraft to an initial trajectory. Parking, transfer, operational and disposal orbits can serve different stages of the mission. The chosen orbit affects coverage, illumination, communications opportunities and propulsion requirements.'),
    p('Ground stations provide command, tracking and telemetry. Mission operations turn observations and plans into commands. The communication architecture connects the space and ground segments. Orbit design therefore interacts with almost every part of the mission.'),
    h('Notation and units'),
    list('r is the relative position vector. Its magnitude r = |r| is a center-to-center distance, usually in km.', 'v = dr/dt is the velocity vector in km/s. Speed v = |v| is a scalar.', 'a is the semi-major axis in km. e is the dimensionless eccentricity.', 'μ is the gravitational parameter in km³/s². G is the universal gravitational constant.', 'ε is the specific mechanical energy in km²/s². h = r × v is the specific angular momentum vector in km²/s.', 'T is the orbital period in seconds. ν is the true anomaly, measured from periapsis in the orbital plane.'),
    p('Use one unit system throughout a calculation. With distance in kilometers and time in seconds, use μ in km³/s². G is commonly tabulated in m³/(kg·s²), so divide it by 10⁹ before combining it with kilometer distances.'),
    h('A useful distinction'),
    p('Kepler’s laws describe the geometry and timing of orbital motion. Newton’s laws explain the force and acceleration that produce it. We first describe the motion, then derive its physical model.'),
    h('Check your understanding'),
    p('A satellite is 500 km above Earth. Is r = 500 km? No: the orbital radius includes Earth’s radius. With the mean-radius convention used in this course, r = 6371 + 500 = 6871 km.'),
  ] },
  { slug: 'astrodynamics-kepler-laws', title: 'Kepler’s three laws', durationMinutes: 15, slides: '19–35', blocks: [
    h('What you will learn'), p('Relate the shape, changing speed and period of an orbit. Use the period law to infer an orbital size or a central mass.'),
    h('From observations to laws'),
    p('Tycho Brahe’s careful observations of Mars gave Johannes Kepler a demanding test of circular models. Kepler treated discrepancies as evidence that the model needed to change. He found that ellipses explained the motion, publishing his first two laws in 1609 and the third in 1619.'),
    h('First law: the shape of the orbit'),
    p('A bound Keplerian orbit is an ellipse with the attracting center at one focus. A circle is the special case e = 0. A noncircular ellipse has 0 < e < 1. Its semi-major axis a describes its size and its eccentricity describes its shape.'),
    f('rₚ = a(1 − e)     rₐ = a(1 + e)     a = (rₚ + rₐ)/2'),
    p('Periapsis is the nearest point and apoapsis the farthest. For Earth orbits, use perigee and apogee. For solar orbits, use perihelion and aphelion. These radii are measured from the attracting center, not from its surface. The line joining the apsides is the line of apsides.'),
    h('Second law: equal areas in equal times'),
    p('The line from the attracting center to the orbiting body sweeps equal areas in equal time intervals. The body moves faster near periapsis and slower near apoapsis. This does not mean equal distances in equal times.'),
    f('dA/dt = h/2     and, at the apsides,     rₚvₚ = rₐvₐ'),
    p('At the apsides, radius and velocity are perpendicular. If apogee is twice as far from the center as perigee, the speed at perigee is twice the speed at apogee. Later we will derive this law from angular momentum conservation.'),
    h('Third law: period and orbital size'),
    f('T = 2π√(a³/μ)     μ = G(M + m)'),
    p('For the same gravitational parameter, T²/a³ is constant. Doubling a multiplies T by 2^(3/2), about 2.83. The period depends on a, not on eccentricity. Neglecting a satellite’s mass is an excellent approximation when m ≪ M, but the exact two-body expression contains both masses.'),
    h('Worked example: the orbit of Mars'),
    p('Take Earth’s orbital period as 1 year and semi-major axis as approximately 1 AU. Mars has a period of 1.88 years. Both planets orbit the Sun and their masses are small compared with the Sun’s.'),
    f('aMars/aEarth = (TMars/TEarth)^(2/3) = 1.88^(2/3) ≈ 1.523'),
    p('Mars therefore has a semi-major axis of about 1.523 AU, or 2.28 × 10⁸ km. The shorthand T² ≈ a³ applies when T is in Earth years and a in AU for solar orbits. It is not a universal formula for arbitrary units or primaries.'),
    h('Worked example: weighing the Sun'),
    f('M + m = 4π²a³/(GT²)'),
    p('Using a = 1.496 × 10¹¹ m, T = 3.156 × 10⁷ s and G = 6.67430 × 10⁻¹¹ m³/(kg·s²) gives about 1.99 × 10³⁰ kg. Neglecting Earth’s mass gives the Sun’s mass. To apply this method to Earth and the Moon, use the Moon’s orbital period, not Earth’s year.'),
    link('Further reading: NASA, Orbits and Kepler’s Laws', 'https://science.nasa.gov/solar-system/orbits-and-keplers-laws/'),
  ] },
  { slug: 'astrodynamics-orbital-periods', title: 'Which orbital period?', durationMinutes: 10, slides: '36–41, 77', blocks: [
    h('What you will learn'), p('Identify the reference event that defines a period and avoid confusing a repeat alignment with a full orbit.'),
    h('Sidereal and Keplerian periods'),
    p('The sidereal period measures a revolution relative to distant stars, approximating an inertial reference. The Keplerian period T = 2π√(a³/μ) comes from the ideal two-body model. In that model, the fixed ellipse returns to its initial position after one period.'),
    h('Synodic period'),
    p('A synodic period measures the time between repeated alignments relative to an observer or another moving body. Successive new moons provide a familiar example. The observer’s own motion matters.'),
    f('1/Tsyn = |1/T₁ − 1/T₂|'),
    p('This expression applies to mean angular rates for bodies moving in the same direction about a common center. For opposite directions, the magnitudes add. Real eccentric or inclined orbits introduce variations in the intervals between individual alignments.'),
    p('The Moon’s sidereal period is about 27.32 days and Earth’s year about 365.256 days. Thus Tsyn ≈ 1 / |1/27.32 − 1/365.256| ≈ 29.53 days. The Moon must travel farther to regain the same alignment with the Sun because Earth has moved.'),
    h('Anomalistic and nodal periods'),
    list('Anomalistic period: time between successive periapsis passages. A rotating line of apsides can make this differ from the sidereal period.', 'Nodal or draconitic period: time between successive crossings of the same reference plane in the same direction, usually ascending-node to ascending-node.', 'In a fixed, unperturbed ellipse these periods coincide when the reference events are defined. Real perturbations can separate them. In a circular orbit, periapsis is not uniquely defined.'),
    p('The Moon’s roughly 18.6-year nodal precession cycle describes the rotation of its orbital plane. It is not the interval between successive ascending-node passages. Likewise, the tropical year follows the equinox, whose precession makes it differ slightly from the sidereal year.'),
    h('Reading orbital data'),
    p('A TLE provides mean motion in revolutions per day as part of the SGP4 model. Dividing 1440 minutes by that number gives a nominal mean period. It should not automatically be interpreted as a Sun-relative synodic period or used as an exact unperturbed orbital element.'),
    p('Historically, the Gaussian gravitational constant helped define astronomical units. Since the IAU’s 2012 definition, 1 AU is exactly 149,597,870,700 m. Modern calculations use a consistent gravitational parameter and unit system.'),
    link('Reference: CelesTrak, Two-Line Element Set Format', 'https://celestrak.org/columns/v04n03/'),
    link('Reference: IAU 2012 Resolution B2, definition of the astronomical unit', 'https://www.iau.org/static/resolutions/IAU2012_English.pdf'),
  ] },
  { slug: 'astrodynamics-newton-laws', title: 'Newton’s laws and free fall', durationMinutes: 15, slides: '42–55, 62', blocks: [
    h('What you will learn'), p('Distinguish mass, weight and momentum, then connect each of Newton’s laws to spacecraft motion.'),
    h('Mass, inertia and momentum'),
    p('Mass m, measured in kilograms, quantifies translational inertia. A large mass resists changes in velocity even when it appears weightless. Linear momentum p = mv, measured in kg·m/s, combines mass and velocity. Rotational inertia is a different quantity: the moment of inertia I depends on how mass is distributed about an axis and has units kg·m².'),
    h('First law: uniform motion without a net force'),
    p('In an inertial frame, an object with no net force keeps a constant velocity. Both speed and direction remain fixed. A satellite on a circular orbit has constant speed but changing direction, so it is accelerating and requires a net force.'),
    f('ΣF = 0  ⇒  dv/dt = 0'),
    h('Second law: force changes momentum'),
    f('ΣF = dp/dt     and, for constant mass,     ΣF = ma'),
    p('The acceleration points in the direction of the net force. The simple form F = ma assumes constant mass for the body being modeled. Rockets expel mass, so their thrust analysis must account for momentum carried away by the exhaust.'),
    h('Third law: forces come in pairs'),
    f('F₁→₂ = −F₂→₁'),
    p('Action and reaction act on different bodies. They therefore do not cancel in the force balance for a single body. A rocket accelerates by ejecting exhaust in the opposite direction and does not need air to push against. Earth attracts a satellite and the satellite attracts Earth with an equal force, but their accelerations differ because their masses differ.'),
    h('Weightlessness is free fall'),
    p('Gravitational weight is W = mg. A 50 kg person has a gravitational weight of about 490 N near Earth’s surface and 81 N on the Moon, while retaining the same mass. Apparent weight is the support force felt or measured by a scale.'),
    p('Inside an orbiting spacecraft, both the astronaut and the spacecraft accelerate under gravity. Little support force is needed, producing apparent weightlessness. Gravity remains substantial at the altitude of the ISS. Free fall is not the absence of gravity.'),
    h('Worked example: pushing a massive spacecraft'),
    p('Following the estimate in the source slides, suppose an 11,110 kg spacecraft changes speed from rest to 0.15 m/s in 6 s. Assume constant mass and approximately constant net force along the direction considered.'),
    f('a = Δv/Δt = 0.15/6 = 0.025 m/s²     F = ma ≈ 278 N'),
    p('The rounded input values give about 278 N, comparable to supporting a 28 kg mass on Earth. A floating object can still require a substantial force to change its motion. The source’s film-based estimate is an illustration, not a precision measurement.'),
    link('Further reading: NASA, What is Microgravity?', 'https://www.nasa.gov/centers-and-facilities/glenn/what-is-microgravity/'),
  ] },
  { slug: 'astrodynamics-gravitation', title: 'Universal gravitation and μ', durationMinutes: 10, slides: '56–61', blocks: [
    h('What you will learn'), p('Calculate gravitational attraction, explain the inverse-square dependence and choose the correct gravitational parameter.'),
    h('The inverse-square force'),
    p('For two point masses separated by a distance r, gravity is attractive, proportional to the product of their masses and inversely proportional to r². Let r point from mass M toward mass m. The force on m is opposite to r.'),
    f('Fg = −GMm r/r³     |Fg| = GMm/r²'),
    p('Doubling the separation reduces the force to one quarter. Doubling one of the masses doubles the force. The distance is measured between centers for the spherical-body approximation, not between surfaces.'),
    h('Why the spherical approximation works'),
    p('Newton’s shell theorem states that the gravitational field outside a spherically symmetric body is the same as if its mass were concentrated at its center. Inside an ideal uniform spherical shell the net field is zero. This is not the same as saying gravity is zero everywhere inside a solid planet.'),
    p('Earth is not perfectly spherical or uniform. The spherical model is the starting point. Its oblateness, higher gravity harmonics and other perturbations are needed for more accurate predictions.'),
    h('G and μ are different quantities'),
    f('G ≈ 6.67430 × 10⁻¹¹ m³/(kg·s²)     μ = G(M + m)'),
    p('G is the universal gravitational constant, measured experimentally. The product GM is the gravitational parameter of a body and can be inferred accurately from orbital observations. For relative motion, both masses enter μ. For an artificial Earth satellite, m ≪ M⊕ and μ ≈ GM⊕.'),
    f('μ⊕ ≈ 398600.4415 km³/s²     g(r) = μ⊕/r²'),
    p('At a 500 km altitude with R⊕ = 6371 km, r = 6871 km. The acceleration is about 0.00844 km/s², or 8.44 m/s². Gravity at orbital altitude is far from zero.'),
    h('When the smaller mass matters'),
    p('For the Earth–Moon system, keeping both masses improves the two-body approximation. For binary systems of comparable mass, omitting one mass would seriously distort the period and relative acceleration. The main criterion is the mass ratio, not the name of the orbiting object.'),
  ] },
  { slug: 'astrodynamics-specific-energy', title: 'Specific mechanical energy', durationMinutes: 15, slides: '63–69', blocks: [
    h('What you will learn'), p('Use conservation of energy to connect speed, distance, orbital size and escape.'),
    h('Energy per unit mass'),
    p('In the ideal two-body gravitational field, kinetic and potential energy exchange while their sum remains constant. Divide the energy by the spacecraft’s mass to define specific mechanical energy. The potential-energy convention sets zero at infinite separation.'),
    f('ε = v²/2 − μ/r     [km²/s²]'),
    p('The kinetic term is nonnegative and the potential term is negative at every finite distance. As a spacecraft approaches periapsis, potential energy decreases and kinetic energy increases. It therefore moves faster. A burn or atmospheric drag changes the mechanical energy, so the conservation statement applies between such effects.'),
    h('Energy and orbital size'),
    f('ε = −μ/(2a)     v² = μ(2/r − 1/a)'),
    p('The second expression is the vis-viva equation. It applies to Keplerian conics, with positive a for ellipses and negative a for hyperbolas. A parabola is the limiting case with ε = 0 and 1/a = 0. Use the local radius r to calculate speed, not the altitude.'),
    list('Circle or ellipse: ε < 0. The trajectory is bound, with 0 ≤ e < 1.', 'Parabola: ε = 0. Escape is just achieved with zero asymptotic speed.', 'Hyperbola: ε > 0. The trajectory is unbound and retains speed far from the primary.'),
    f('vcircular = √(μ/r)     vescape = √(2μ/r)'),
    h('Worked example: a geostationary-altitude orbit'),
    p('For this rounded comparison, take altitude H = 35,786 km and mean Earth radius R⊕ = 6371 km. Then a = r = 42,157 km for a circular orbit. Using the equatorial radius is more appropriate for precise GEO work, but changes this rounded energy only slightly.'),
    f('ε = −398600.4415 / (2 × 42157) ≈ −4.728 km²/s²'),
    p('At a 430 km circular altitude, a = 6801 km and ε ≈ −29.30 km²/s². The lower orbit has a higher speed but a more negative total specific energy. Raising an orbit requires adding energy.'),
    h('Why “slow down to speed up” needs context'),
    p('A retrograde burn immediately decreases speed at the burn location. It can place the spacecraft on an ellipse with a lower periapsis, where gravity later increases its speed. A lower circular orbit has a greater circular speed, but reaching it generally requires a second burn. Separate the immediate velocity change from the speed elsewhere on the new orbit.'),
    p('Earth’s potential term does not suddenly become zero at the edge of its sphere of influence. It approaches zero only as r tends to infinity in the isolated two-body model. Interplanetary trajectory models change the dominant primary rather than switching gravity off.'),
    h('Energy alone does not fix the shape'),
    f('e = √(1 + 2εh²/μ²)'),
    p('Energy fixes a. Together, energy and angular momentum determine eccentricity. Different ellipses can share the same energy and period while having different periapsis distances.'),
  ] },
  { slug: 'astrodynamics-angular-momentum', title: 'Specific angular momentum', durationMinutes: 15, slides: '70–74', blocks: [
    h('What you will learn'), p('Calculate the specific angular momentum and explain why an unperturbed orbit remains in a fixed plane.'),
    h('The vector perpendicular to the orbit'),
    f('h = r × v     [km²/s]'),
    p('Specific angular momentum is angular momentum per unit mass. Its direction follows the right-hand rule and is perpendicular to both position and velocity. The full angular momentum is L = mh, with the appropriate consistent mass and distance units.'),
    h('Conservation under a central force'),
    f('dh/dt = v × v + r × r̈ = 0'),
    p('The first cross product is zero because a vector is parallel to itself. The second is zero because gravitational acceleration is radial. Thus both the magnitude and direction of h remain constant. Position and velocity stay in the plane perpendicular to h.'),
    p('A conservative force conserves mechanical energy. A central force conserves angular momentum. Ideal two-body gravity has both properties. Perturbations that exert torque about the primary can change the orbit plane.'),
    h('Equivalent formulas'),
    f('h = rv sin θ = rv cos γ     h = √(μp) = √(μa(1 − e²))'),
    p('θ is the angle between r and v. The flight-path angle γ is measured from the local horizontal, so θ = 90° − γ. The semi-latus rectum p = a(1 − e²) describes the conic. These expressions concern the magnitude h.'),
    f('At the apsides: h = rₚvₚ = rₐvₐ     Areal rate: dA/dt = h/2'),
    h('Worked example: a 500 km circular orbit'),
    p('Use R⊕ = 6371 km and μ⊕ = 398600.4415 km³/s². Then r = 6871 km and v = √(μ/r) ≈ 7.617 km/s. Radius and velocity are perpendicular.'),
    f('h = rv = √(μr) ≈ 52,333 km²/s'),
    p('This value is independent of spacecraft mass in the test-particle approximation. Comparing specific angular momenta of a small satellite and the Moon therefore compares orbital geometry and speed, not their total angular momenta.'),
    h('A practical consequence'),
    p('Changing the orbital plane requires changing the direction of velocity and therefore h. For an ideal instantaneous plane change by angle Δi at equal initial and final speed, Δv = 2v sin(Δi/2). It is less costly in velocity change where orbital speed is lower. Fuel cost additionally depends on propulsion performance and mass, so no universal fuel mass follows from an inclination change alone.'),
  ] },
  { slug: 'astrodynamics-relative-motion', title: 'The two-body equation of relative motion', durationMinutes: 15, slides: '75–80', blocks: [
    h('What you will learn'), p('Derive the relative acceleration of two gravitating bodies and state when the resulting orbit model is useful.'),
    h('Define the relative position'),
    p('Let xM and xm be the positions of masses M and m in an inertial frame. Define r = xm − xM, pointing from M toward m. Newton’s third law gives equal and opposite forces, but the two accelerations have different magnitudes.'),
    f('ẍm = −GM r/r³     ẍM = +Gm r/r³'),
    h('Subtract the accelerations'),
    f('r̈ = ẍm − ẍM = −G(M + m) r/r³ = −μr/r³'),
    p('Both masses appear naturally. When m ≪ M, μ ≈ GM and the primary-centered approximation becomes very accurate. The denominator r³ does not mean an inverse-cube force: the numerator is a vector of length r, giving an acceleration magnitude μ/r².'),
    h('The initial-value problem'),
    f('dr/dt = v     dv/dt = −μr/r³'),
    p('A position vector and a velocity vector at a specified epoch provide six scalar initial conditions. Together with μ, they determine an ideal two-body trajectory. Numerical orbit propagation integrates these coupled equations. Energy and angular momentum provide useful checks on an unperturbed numerical solution.'),
    h('Assumptions and limits'),
    list('Only the mutual gravity of two bodies acts. Third-body attraction, drag, radiation pressure and thrust are omitted.', 'Bodies are point masses or spherically symmetric bodies observed externally. Earth’s oblateness is omitted.', 'Masses remain constant and Newtonian mechanics applies in an inertial framework.', 'A negligible satellite mass is an additional approximation. It is not required for the exact two-body relative equation with μ = G(M + m).'),
    p('This model is a powerful baseline, but its errors accumulate when neglected forces matter. For example, oblateness can rotate the orbital plane, drag can lower an orbit, and a thrust maneuver changes its energy and angular momentum.'),
    h('The barycenter'),
    f('Rcm = (M xM + m xm)/(M + m)     dM = [m/(M + m)] d'),
    p('The center of mass, or barycenter, is the common point about which both bodies move. If xM = 0 and the separation is d, the barycenter lies a distance dM from M toward m. A very small mass ratio puts it close to the larger body’s center.'),
    p('Using M⊕ = 5.97 × 10²⁴ kg, mMoon = 7.35 × 10²² kg and d = 384,400 km gives dM ≈ 4675 km, inside Earth. The value varies with separation. For an artificial satellite, the displacement of Earth’s center from the barycenter is negligible on ordinary orbital scales.'),
    h('Putting the laws together'),
    p('Newton’s laws and gravitation yield the two-body equation. Its conserved energy and angular momentum lead to conic trajectories, equal areas in equal times and Kepler’s period law. The observational and dynamical descriptions are therefore consistent parts of the same model.'),
  ] },
  { slug: 'astrodynamics-practice', title: 'Worked practice and key takeaways', durationMinutes: 15, slides: '33–34, 47, 73, 81–85', blocks: [
    h('How to work through the practice'),
    p('Write down the model, input units and formula before substituting numbers. Use μ⊕ = 398600.4415 km³/s² and R⊕ = 6371 km unless stated otherwise. The following exercises include solutions. A separate self-check follows below.'),
    h('Exercise 1: locate the apsides'),
    p('An elliptical Earth orbit has a = 10,000 km and e = 0.25. Find perigee and apogee radii and altitudes.'),
    f('rₚ = 10000(1 − 0.25) = 7500 km     rₐ = 10000(1 + 0.25) = 12500 km'),
    p('Subtract Earth’s radius: Hₚ = 1129 km and Hₐ = 6129 km. The values 7500 km and 12,500 km describe distances from Earth’s center. Confusing them with altitudes changes the physical orbit.'),
    h('Exercise 2: speed at each apsis'),
    p('For the same orbit, use vis-viva to calculate the two speeds, then check angular momentum conservation.'),
    f('vₚ = √[398600.4415(2/7500 − 1/10000)] ≈ 8.151 km/s'),
    f('vₐ = √[398600.4415(2/12500 − 1/10000)] ≈ 4.890 km/s'),
    p('The ratio vₚ/vₐ = rₐ/rₚ ≈ 1.667. Both rₚvₚ and rₐvₐ give h ≈ 61,130 km²/s. Agreement is an independent check on the calculation.'),
    h('Exercise 3: period and energy'),
    f('T = 2π√(10000³/398600.4415) ≈ 9952 s ≈ 165.9 min'),
    f('ε = −398600.4415/(2 × 10000) ≈ −19.930 km²/s²'),
    p('Now imagine a circle with the same semi-major axis. It has the same energy and period, even though the original ellipse has a changing radius and speed. Changing eccentricity alone at fixed a does not change the Keplerian period.'),
    h('Exercise 4: how much gravity remains?'),
    p('At an altitude of 500 km, compute gravity and explain why a freely orbiting astronaut floats.'),
    f('g = 398600.4415/6871² ≈ 0.008443 km/s² = 8.443 m/s²'),
    p('The astronaut and spacecraft fall together, so the apparent support force is small. Their shared gravitational acceleration is not small. Mass and inertia remain present.'),
    h('Your equation reference'),
    list('Keplerian period: T = 2π√(a³/μ).', 'Gravitational acceleration: r̈ = −μr/r³, with μ = G(M + m).', 'Specific energy: ε = v²/2 − μ/r = −μ/(2a).', 'Vis-viva: v² = μ(2/r − 1/a).', 'Specific angular momentum: h = r × v, in km²/s.', 'Elliptical apsides: rₚ = a(1 − e), rₐ = a(1 + e).', 'Areal rate: dA/dt = h/2.'),
    h('Before continuing'),
    p('You should now be able to explain why satellites remain in orbit, calculate the basic properties of a two-body trajectory and recognize the limits of that approximation. Orbital geometry, anomalies and the Kepler problem build on these results in later modules.'),
  ] },
]

export const astrodynamicsLessons = lessons.map(({ blocks, slides, ...lesson }, index) => ({
  ...lesson, order: (index + 1) * 10,
  content: richText([...blocks, h('Source'), p(`Adapted from Richard L. Lachance, Ph.D., SꙨL Part II – Section 1 – Astrodynamics Laws, slides ${slides}. Equations use consistent vector notation and units. Numerical examples use explicitly stated approximations.`)]),
}))

export const astrodynamicsQuiz = {
  title: 'Astrodynamics Laws · Self-check', slug: 'astrodynamics-laws-self-check', order: 10, passingScore: 70,
  instructions: richText([p('A practice self-check adapted from the questions in slides 81–85. Select one answer per question. Check your responses to see explanations. This is practice, not a recorded assessment.')]),
  questions: [
    ['Who established the empirical law of elliptical planetary orbits?', ['Kepler', 'Newton', 'Brahe', 'Copernicus'], 0, 'Kepler formulated the law using observations, notably those of Mars collected by Brahe. Newton later explained it dynamically.'],
    ['Which pair gives the two-body equation of relative motion?', ['Newton’s first law and Kepler’s third law', 'Newton’s second law and universal gravitation', 'Kepler’s first and second laws alone', 'Newton’s third law and the law of areas alone'], 1, 'Combining gravitational forces with mass times acceleration, then subtracting the two accelerations, gives r̈ = −G(M + m)r/r³.'],
    ['If the distance between two point masses doubles, the gravitational force becomes…', ['Twice as large', 'Half as large', 'One quarter as large', 'Unchanged'], 2, 'Gravity follows an inverse-square law: 1/(2r)² = 1/(4r²).'],
    ['For a = 10,000 km and e = 0.25, what is the perigee radius?', ['2500 km', '7500 km', '10,000 km', '12,500 km'], 1, 'rₚ = a(1 − e) = 7500 km, measured from Earth’s center.'],
    ['What is the specific energy of a circular orbit at approximately GEO altitude?', ['+4.73 km²/s²', '−19.9 km²/s²', '−4.73 km²/s²', 'Zero'], 2, 'For a ≈ 42,160 km, ε = −μ/(2a) ≈ −4.73 km²/s². The negative sign indicates a bound orbit.'],
    ['At a fixed state (r, v), what happens to specific energy when spacecraft mass doubles, neglecting its contribution to μ?', ['It doubles', 'It is halved', 'It becomes positive', 'It is unchanged'], 3, 'Specific energy is energy per unit spacecraft mass. With μ fixed, ε depends only on r and v.'],
    ['Which effect is omitted from the unperturbed two-body model?', ['Mutual gravitation', 'Acceleration of both bodies', 'The Moon’s attraction in an Earth–satellite model', 'Conservation of angular momentum'], 2, 'Including the Moon as an additional attracting body introduces a third-body perturbation.'],
    ['Which eccentricity describes a noncircular ellipse?', ['0.5', '1', '1.5', '−0.5'], 0, 'A noncircular ellipse has 0 < e < 1. A circle has e = 0, a parabola e = 1 and a hyperbola e > 1.'],
    ['What does a constant angular momentum vector tell us?', ['Speed is constant everywhere', 'The orbital plane remains fixed', 'The orbit must be circular', 'Gravity vanishes at apogee'], 1, 'The direction of h is perpendicular to the orbit plane. If that direction is fixed, so is the plane.'],
    ['What assumption is required to reduce dp/dt to m dv/dt?', ['Constant force', 'Constant velocity', 'Constant mass', 'Zero gravity'], 2, 'For constant mass, differentiating p = mv gives dp/dt = m dv/dt.'],
  ].map(([prompt, choices, correct, explanation]) => ({
    prompt: prompt as string,
    choices: (choices as string[]).map((text, index) => ({ text, isCorrect: index === correct })),
    explanation: richText([p(explanation as string)]),
  })),
}
